# Question 1.

# Ans. 

In [3]:
import numpy as np
print(np.arange(2,50,3))


[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Quetion 2

# Ans.


In [4]:
import numpy 

list1 = int(input("enter the size of list"))
num_list1 = list(int(num)for num in input("enter the number list:").strip().split())
print("first list",num_list1)
print(" ")

list2 = int(input("enter the size of list")) 
num_list2 = list(int(num)for num in input("enter the number list:").strip().split())
print("first list",num_list2)
print(" ")

array1 = numpy.array(num_list1)
print("array1 as numpy array", array1)

array2 = numpy.array(num_list2)
print("array2 as numpy array", array2)
print(" ")

concatenated_array = numpy.concatenate((array1,array2), axis=0)
print("concatenated array",concatenated_array)
print(" ")

concatenated_array.sort()
print("sorted array", concatenated_array)


enter the size of list5
enter the number list:1 2 3 4 5
first list [1, 2, 3, 4, 5]
 
enter the size of list5
enter the number list:6 7 8 9 10
first list [6, 7, 8, 9, 10]
 
array1 as numpy array [1 2 3 4 5]
array2 as numpy array [ 6  7  8  9 10]
 
concatenated array [ 1  2  3  4  5  6  7  8  9 10]
 
sorted array [ 1  2  3  4  5  6  7  8  9 10]


# Question 3

# Ans

In [6]:
import numpy as np
arr_2d = np.array([[1 ,2 , 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("2D array")
print(arr_2d)
print(" ")

rows = np.size(arr_2d, 0)
print ("Number of Rows: ", rows)

columns = np.size(arr_2d, 1)
print("Number of columns: ", columns)

2D array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
Number of Rows:  3
Number of columns:  4


# Quetion 4.

# Ans.

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("1D array: ")
print (arr)
print(" ")

arr_2d = np.reshape(arr,(3,3))
print("2D Array")
print(arr_2d)

1D array: 
[1 2 3 4 5 6 7 8 9]
 
2D Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Question 5.

# Ans.


In [15]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print("Vertical stack:\n",np.vstack((a,b)))
print(" ")
print("Horizontal stack:\n",np.hstack((a,b)))


Vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
 
Horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]


# Quetion 6.

# Ans.


In [16]:
 def unique(list1):
        x = np.array(list1)
        print(np.unique(x))
        
list1 = [ 1, 2, 3, 4, 5, 6, 7, 8, 4, 2, 3]
print("unique value: ")
unique(list1)

list2 = set(list1)
print ("No. of unique list", len(list2))

unique value: 
[1 2 3 4 5 6 7 8]
No. of unique list 8
